blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/VamshiKrishnaMacha/Intelligent-Road-Infrastructure-Assessment-Using-YOLO/discussions
    about: Please ask questions and start discussions here